# Generated by Django 2.0.1 on 2018-10-04 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagefile',
            options={'ordering': ['-upload_time'], 'verbose_name': '画像ファイル', 'verbose_name_plural': '画像ファイル'},
        ),
    ]
