# Generated by Django 2.0.1 on 2018-10-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_form', '0002_auto_20181004_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='projects_name',
            field=models.CharField(default='overload', max_length=20),
            preserve_default=False,
        ),
    ]
