# Generated by Django 2.0.1 on 2018-10-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_form', '0004_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='file_path',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
