# Generated by Django 2.0.1 on 2018-10-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_form', '0005_auto_20181011_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='extension',
            field=models.CharField(default='.png', max_length=10),
            preserve_default=False,
        ),
    ]
