# Generated by Django 2.0.1 on 2018-10-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_form', '0006_file_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='thumbnail_path',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
