# Generated by Django 2.0.1 on 2018-10-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_form', '0007_file_thumbnail_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageFile',
        ),
        migrations.AddField(
            model_name='file',
            name='category',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
