# Generated by Django 2.0.1 on 2018-10-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_form', '0008_auto_20181022_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.CharField(choices=[('テクスチャ', 'テクスチャ'), ('モデル', 'モデル'), ('エフェクト', 'エフェクト')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
